apiVersion: v1
kind: Pod
metadata:
  name: node-todo
  namespace: node-todo-ns
spec:
  containers:
  - name: node-todo
    image: utkarshpathak/node-todo-app-cicd:latest
    ports:
    - containerPort: 8000
